[General]
loglevel = notify
internet-test-url = http://wifi.vivo.com.cn/generate_204
proxy-test-url = http://1.1.1.1/generate_204
test-timeout = 5
dns-server = 223.5.5.5, 119.29.29.29
hijack-dns = *:53
udp-policy-not-supported-behaviour = REJECT
udp-priority = false
exclude-simple-hostnames = true
geoip-maxmind-url = https://raw.githubusercontent.com/Loyalsoldier/geoip/release/Country-without-asn.mmdb
ipv6 = false
ipv6-vif = disabled

[Proxy Group]
𝗣𝗿𝗼𝘅𝘆 = select, no-alert=0, hidden=0, include-all-proxies=0, icon-url=https://raw.githubusercontent.com/lige47/QuanX-icon-rule/main/icon/02ProxySoftLogo/Surge(9).png, policy-path=https://liangxin.xyz/api/v1/liangxin?OwO=67266d13e4143354ea889664abbcac80, update-interval=10800, policy-regex-filter=^((?!(套餐|订阅|到期|客户端|支持|流量)).)*$
𝗧𝗲𝗹𝗲𝗴𝗿𝗮𝗺 = smart, no-alert=1, hidden=1, persistent=1, icon-url=B1::Logos::Telegram App
𝗔𝗜 = fallback, hidden=1, no-alert=1, icon-url=B1::Logos::ChatGPT
𝗔𝗽𝗽𝗹𝗲!𝗖𝗡 = smart, no-alert=0, hidden=1, icon-url=B1::Plants::Bitten Apple
𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸 = fallback, hidden=1, no-alert=1, icon-url=B1::Messaging::Delete Link
𝗙𝗶𝗻𝗮𝗹 = fallback, 𝗣𝗿𝗼𝘅𝘆, 𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸, DIRECT, no-alert=1, hidden=1, icon-url=B1::Industry::Broken Robot

[Rule]
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/Porn.list,𝗣𝗿𝗼𝘅𝘆
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/Direct.list,DIRECT
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/Reject.list,REJECT,pre-matching
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/Google.list,𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/Github.list,𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/Microsoft.list,𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/AI.list,𝗔𝗜
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/Telegram.list,𝗧𝗲𝗹𝗲𝗴𝗿𝗮𝗺
AND,((IN-PORT,6153), (HOSTNAME-TYPE,IPv4)),REJECT-DROP // Fuck Telegram
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/Twitter.list,𝗙𝗮𝗹𝗹𝗕𝗮𝗰𝗸
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/Proxy.list,𝗣𝗿𝗼𝘅𝘆
RULE-SET,https://cdn.jsdelivr.net/gh/Repcz/Tool@X/Surge/Rules/AppleServers.list,𝗔𝗽𝗽𝗹𝗲!𝗖𝗡
RULE-SET,LAN,DIRECT
GEOIP,CN,DIRECT
FINAL,𝗙𝗶𝗻𝗮𝗹

[SSID Setting]
SSID:MLGS_5G suspend=true

[MITM]
h2 = true